version: "3.1"
services:
  web:
    build: ./docker/web
    command: python -u app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - db
  db:
    image: mongo:3.0.2
    ports:
      - "27017:27017"
    volumes:
      - mongodb-datavolume:/data/db

volumes:
  mongodb-datavolume:
